window.SomaDashboard={cacheKey:null,cache:null,
  stats(vehicles){const key=vehicles.length+'|'+vehicles.map(v=>v.id+':'+v.score+':'+v.decision).join(','); if(this.cacheKey===key&&this.cache)return this.cache; const ages=vehicles.map(v=>v.age).filter(Number.isFinite); const byType=SomaUtils.countBy(vehicles,'type'); const byAgency={}; vehicles.forEach(v=>{if(!byAgency[v.agence])byAgency[v.agence]={count:0,ages:[],critical:0}; byAgency[v.agence].count++; if(Number.isFinite(v.age))byAgency[v.agence].ages.push(v.age); if(v.score>=70)byAgency[v.agence].critical++;}); const st={n:vehicles.length,ageAvg:SomaUtils.avg(ages),ageMed:SomaUtils.median(ages),critical:vehicles.filter(v=>v.decision==='Remplacer').length,ctSoon:vehicles.filter(v=>v.ctDays!=null&&v.ctDays>=0&&v.ctDays<=SomaApp.settings.ctDays).length,ctExpired:vehicles.filter(v=>v.ctDays!=null&&v.ctDays<0).length,taxiSoon:vehicles.filter(v=>v.taxiDays!=null&&v.taxiDays>=0&&v.taxiDays<=SomaApp.settings.ctDays).length,taxiExpired:vehicles.filter(v=>v.taxiDays!=null&&v.taxiDays<0).length,agencies:new Set(vehicles.map(v=>v.agence).filter(Boolean)).size,byType,byAgency,ages}; this.cacheKey=key; this.cache=st; return st;},
  render(vehicles,importInfo){const filtered=SomaFilters.apply(vehicles); const st=this.stats(filtered); document.getElementById('kpis').innerHTML=[['Véhicules',st.n,'filtrés'],['Âge moyen',st.ageAvg.toFixed(1)+' ans','base 01/01/2027'],['Âge médian',st.ageMed.toFixed(1)+' ans','distribution'],['Critiques',st.critical,'à remplacer'],['CT dépassés',st.ctExpired,'réglementaire'],['CT <60 j',st.ctSoon,'échéance proche'],['Taximètres <60 j',st.taxiSoon,'échéance proche']].map(k=>`<div class="kpi"><div class="label">${k[0]}</div><div class="value">${k[1]}</div><div class="note">${k[2]}</div></div>`).join('');
    const byAgencyAvg=Object.entries(st.byAgency).map(([label,o])=>({label,value:Number(SomaUtils.avg(o.ages).toFixed(1))})).sort((a,b)=>b.value-a.value).slice(0,10); SomaCharts.bars('barsOldAgency',byAgencyAvg);
    const buckets={'0-3':0,'3-5':0,'5-7':0,'7-9':0,'>9':0}; filtered.forEach(v=>{const a=v.age; if(!Number.isFinite(a))return; if(a<3)buckets['0-3']++; else if(a<5)buckets['3-5']++; else if(a<7)buckets['5-7']++; else if(a<9)buckets['7-9']++; else buckets['>9']++;}); SomaCharts.bars('barsAge',Object.entries(buckets).map(([label,value])=>({label,value})));
    const ct={OK:0,Proche:0,Dépassé:0,Inconnu:0}; filtered.forEach(v=>ct[SomaUtils.dateStatus(v.ctDays,SomaApp.settings.ctDays)]++); SomaCharts.distribution('ctDistribution',Object.entries(ct).map(([label,value])=>({label,value,percent:SomaUtils.pct(value,st.n)})));
    const tx={OK:0,Proche:0,Dépassé:0,Inconnu:0}; filtered.forEach(v=>{if(SomaUtils.norm(v.type).includes('taxi'))tx[SomaUtils.dateStatus(v.taxiDays,SomaApp.settings.ctDays)]++;}); const totalTx=Object.values(tx).reduce((a,b)=>a+b,0); SomaCharts.distribution('taxiDistribution',Object.entries(tx).map(([label,value])=>({label,value,percent:SomaUtils.pct(value,totalTx)})));
    SomaCharts.distribution('typeDistribution',Object.entries(st.byType).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([label,value])=>({label,value,percent:SomaUtils.pct(value,st.n)}))); SomaCharts.miniList('topCritical',filtered.slice().sort((a,b)=>b.score-a.score).slice(0,10)); this.renderScenario(vehicles); this.renderSummary(filtered); if(importInfo)this.renderImport(importInfo,st);},
  renderScenario(vehicles){return;},
  renderSummary(vehicles){const n=vehicles.length; if(!n)return; const st=this.stats(vehicles); document.getElementById('aiSummary').innerHTML=`<b>Lecture automatique :</b> ${st.critical} véhicules sont classés en remplacement prioritaire sur ${n} véhicules filtrés. L'âge moyen est de ${st.ageAvg.toFixed(1)} ans. Les alertes réglementaires identifiées portent sur ${st.ctExpired} CT dépassés et ${st.ctSoon} CT proches.`;},
  renderImport(info,st){const v=info.validation||{}; document.getElementById('dataQuality').innerHTML=`<div class="qualityScore ${v.quality>=95?'green':v.quality>=85?'blue':v.quality>=70?'orange':'red'}"><b>${v.quality||0}%</b><span>Qualité des données · ${v.label||'—'}</span></div>`; const byType=SomaUtils.countBy(info.vehicles,'type'); const cards=[['Importés',info.vehicles.length,info.sheetName],['Valides',v.valid||0,'hors anomalies'],['Anomalies',(v.anomalies||[]).length,v.label||''],...Object.entries(byType).slice(0,5).map(([k,val])=>[k,val,'type'])]; document.getElementById('importReport').innerHTML=`<div class="reportGrid">${cards.map(c=>`<div class="reportItem"><div class="label">${SomaUtils.escape(c[0])}</div><div class="value">${SomaUtils.escape(c[1])}</div><div class="note">${SomaUtils.escape(c[2]||'')}</div></div>`).join('')}</div>`; this.renderAnomalies(info);},
  renderAnomalies(info){const an=(info.validation?.anomalies||[]); document.getElementById('anomalyPanel').innerHTML=an.length?an.slice(0,120).map(a=>`<div class="anomalyLine" data-row="${a.row}"><b>Ligne ${a.row}</b><span>${SomaUtils.escape(a.category||a.type)}</span><em>${SomaUtils.escape(a.message)}</em></div>`).join(''):'<div class="emptyState">Aucune anomalie détectée.</div>';},
  renderAnomalyCenter(){const an=(SomaApp.state.importInfo?.validation?.anomalies||[]); const groups={}; an.forEach(a=>(groups[a.category||'Autres']=groups[a.category||'Autres']||[]).push(a)); document.getElementById('anomalyCenter').innerHTML=`<h2>Centre des anomalies</h2><p class="hint">Clique une catégorie pour filtrer visuellement les lignes concernées.</p>${Object.entries(groups).map(([cat,items])=>`<div class="anomGroup"><h3>${cat} · ${items.length}</h3>${items.slice(0,80).map(a=>`<button class="anomBtn" onclick="SomaTable.focusRow('${a.vehicle?.id||''}')">Ligne ${a.row} · ${SomaUtils.escape(a.message)}</button>`).join('')}</div>`).join('')||'<div class="emptyState">Aucune anomalie.</div>'}`;}
};
