window.SomaOptimizer={
  cache:new Map(),
  strategies:{
    patrimoine:{label:'Patrimoine',desc:'Priorité au rajeunissement',w:{score:1.0,age:3.2,reg:1.0,type:0.8,roi:0.3,balance:0.6}},
    securite:{label:'Sécurité',desc:'Priorité au risque réglementaire',w:{score:1.8,age:1.1,reg:4.0,type:1.0,roi:0.2,balance:0.4}},
    exploitation:{label:'Exploitation',desc:'Priorité à la disponibilité opérationnelle',w:{score:1.7,age:1.3,reg:1.8,type:2.4,roi:0.4,balance:0.7}},
    financier:{label:'Financier',desc:'Priorité au retour sur investissement',w:{score:1.0,age:1.0,reg:1.0,type:0.3,roi:3.6,balance:0.3}},
    equilibre:{label:'Équilibre territorial',desc:'Réduction des écarts entre agences',w:{score:1.2,age:1.2,reg:1.1,type:0.6,roi:0.2,balance:3.2}},
    libre:{label:'Libre',desc:'Compromis paramétrable',w:{score:1.45,age:1.55,reg:1.75,type:1.1,roi:1.0,balance:1.0}}
  },
  defaults:{budgetMax:2000000,maxVehicles:999,agencyCap:0,regionCap:0,typeCap:0,minAmb:0,minVsl:0,ageTarget:5.5,healthTarget:75,amortYears:5},
  readConstraints(){const g=id=>Number(document.getElementById(id)?.value)||0; return {...this.defaults,budgetMax:g('optBudget')||this.defaults.budgetMax,maxVehicles:g('optMaxVehicles')||this.defaults.maxVehicles,agencyCap:g('optAgencyCap'),regionCap:g('optRegionCap'),typeCap:g('optTypeCap'),minAmb:g('optMinAmb'),minVsl:g('optMinVsl'),ageTarget:g('optAgeTarget')||this.defaults.ageTarget,healthTarget:g('optHealthTarget')||this.defaults.healthTarget,amortYears:Number(document.getElementById('amortYears')?.value)||5};},
  key(vehicles,constraints){return vehicles.length+'|'+vehicles.map(v=>`${v.id}:${v.score}:${v.age}:${v.ctDays}:${v.taxiDays}`).join(',')+'|'+JSON.stringify(constraints);},
  compareStrategies(vehicles,constraints=this.readConstraints()){const key=this.key(vehicles,constraints); if(this.cache.has(key))return this.cache.get(key); const rows=Object.keys(this.strategies).map(id=>this.optimize(vehicles,constraints,id)); const best=this.bestCompromise(rows); const plan=this.fiveYearPlan(vehicles,best,constraints); const patrimony=this.patrimony(vehicles,rows,plan,constraints); const out={strategies:rows,best,plan,patrimony,explanations:this.explanations(rows,best,plan,patrimony)}; this.cache.set(key,out); return out;},
  optimize(vehicles,constraints,strategyId='libre'){const strat=this.strategies[strategyId]||this.strategies.libre; const params=SomaSimulator.readParams?SomaSimulator.readParams():SomaSimulator.defaults; const baseStats=SomaDashboard.stats(vehicles); const agencyRisk=this.agencyRisk(vehicles); let budgetLeft=constraints.budgetMax, maxLeft=constraints.maxVehicles; const selected=[], excluded=[]; const spentAgency={}, spentType={}, spentRegion={}; const candidates=vehicles.filter(v=>v.score>=40||v.decision!=='Conserver').map(v=>this.decorate(v,params,agencyRisk,strat)).sort((a,b)=>b.optimScore-a.optimScore);
    for(const v of candidates){const region=this.regionOf(v); const hard=[]; if(maxLeft<=0)hard.push('Nombre maximal de véhicules atteint'); if(v.net>budgetLeft)hard.push('Budget insuffisant'); if(constraints.agencyCap&&((spentAgency[v.agence]||0)+v.net>constraints.agencyCap))hard.push('Plafond agence atteint'); if(constraints.typeCap&&((spentType[v.typeNorm]||0)+v.net>constraints.typeCap))hard.push('Plafond type atteint'); if(constraints.regionCap&&((spentRegion[region]||0)+v.net>constraints.regionCap))hard.push('Plafond région atteint'); if(hard.length){excluded.push({...v,excludeReason:hard.join(' · ')}); continue;} selected.push({...v,selectionReason:this.justifyVehicle(v,strategyId)}); budgetLeft-=v.net; maxLeft--; spentAgency[v.agence]=(spentAgency[v.agence]||0)+v.net; spentType[v.typeNorm]=(spentType[v.typeNorm]||0)+v.net; spentRegion[region]=(spentRegion[region]||0)+v.net;}
    const after=this.afterVehicles(vehicles,selected); const statsAfter=SomaDashboard.stats(after); const healthBefore=SomaExecutive.healthIndex?SomaExecutive.healthIndex(vehicles,baseStats,SomaExecutive.agencyScores(vehicles)): {score:0}; const healthAfter=SomaExecutive.healthIndex?SomaExecutive.healthIndex(after,statsAfter,SomaExecutive.agencyScores(after)): {score:0}; const budgetBrut=selected.reduce((s,v)=>s+v.replaceCost,0), repriseEstimee=selected.reduce((s,v)=>s+v.resale,0), investissementNet=budgetBrut-repriseEstimee; const economies=selected.reduce((s,v)=>s+(v.score>=80?1500:v.score>=60?800:350),0); const roi=investissementNet?Math.round(economies/investissementNet*10000)/100:0; const result={id:strategyId,strategyName:strat.label,description:strat.desc,budgetBrut,repriseEstimee,investissementNet,budgetRestant:budgetLeft,vehiculesRetenus:selected,vehiculesExclus:excluded,statsAvant:{ageAvg:baseStats.ageAvg,critical:baseStats.critical,n:vehicles.length,health:healthBefore.score},statsApres:{ageAvg:statsAfter.ageAvg,critical:statsAfter.critical,n:after.length,health:healthAfter.score},repartitionParAgence:SomaUtils.countBy(selected,'agence'),repartitionParType:SomaUtils.countBy(selected,'typeNorm'),consequences:this.consequences(vehicles,selected,excluded,healthBefore,healthAfter,baseStats,statsAfter),impact:{economies,roi,amortAnnual:investissementNet/(constraints.amortYears||5),amortMonthly:investissementNet/(constraints.amortYears||5)/12}}; result.compromiseScore=this.compromiseScore(result,constraints); return result;},
  decorate(v,params,agencyRisk,strat){const typeNorm=SomaSimulator.normalizeType(v.type); const p=params.types?.[typeNorm]||SomaSimulator.defaults.types[typeNorm]||SomaSimulator.defaults.types.Autre; const net=Math.max(0,p.cost-p.resale); const reg=(v.ctDays!=null&&v.ctDays<0?30:0)+(v.ctDays!=null&&v.ctDays<=60&&v.ctDays>=0?15:0)+(v.taxiDays!=null&&v.taxiDays<=60?10:0); const typePriority=typeNorm==='Ambulance'?18:typeNorm==='VSL'?10:typeNorm==='Taxi'?7:4; const savings=(v.score>=80?1500:v.score>=60?800:350); const roi=net?savings/net*1000:0; const balance=agencyRisk[v.agence]||0; const w=strat.w; const optimScore=(v.score||0)*w.score+(v.age||0)*w.age+reg*w.reg+typePriority*w.type+roi*w.roi+balance*w.balance; return {...v,typeNorm,replaceCost:p.cost,resale:p.resale,net,regulatoryPoints:reg,optimScore};},
  agencyRisk(vehicles){const ag=SomaExecutive.agencyScores?SomaExecutive.agencyScores(vehicles):[]; const out={}; ag.forEach(a=>out[a.agence]=a.score); return out;},
  regionOf(v){return String(v.region||v.region_id||v.directionRegionale||v.agence||'Réseau').split(/[-–\/]/)[0].trim()||'Réseau';},
  afterVehicles(vehicles,selected){const ids=new Set(selected.map(v=>v.id)); return vehicles.map(v=>ids.has(v.id)?{...v,age:1.5,score:0,decision:'Remplacé',ctDays:365,taxiDays:v.taxiDays==null?null:365}:v);},
  compromiseScore(r,constraints){const hGain=(r.statsApres.health-r.statsAvant.health)*3; const critGain=(r.statsAvant.critical-r.statsApres.critical)*1.8; const ageGain=(r.statsAvant.ageAvg-r.statsApres.ageAvg)*10; const budgetPenalty=r.investissementNet/Math.max(1,constraints.budgetMax)*25; return Math.round((hGain+critGain+ageGain+r.impact.roi*2-budgetPenalty)*10)/10;},
  bestCompromise(rows){return rows.slice().sort((a,b)=>b.compromiseScore-a.compromiseScore)[0]||null;},
  consequences(vehicles,selected,excluded,hBefore,hAfter,stBefore,stAfter){const selectedIds=new Set(selected.map(v=>v.id)); const reportCritical=excluded.filter(v=>v.score>=80).length; return {improved:[`Health Index ${hBefore.score}/100 → ${hAfter.score}/100`,`${stBefore.critical-stAfter.critical} véhicules critiques traités`,`${selected.length} renouvellements priorisés`],degraded:[selected.length?'CAPEX mobilisé et amortissements futurs':'Aucun renouvellement significatif', reportCritical?`${reportCritical} véhicules critiques restent reportés`:'Risque critique résiduel limité'],accepted:[`${vehicles.length-selected.length} véhicules conservés temporairement`,`${excluded.length} investissements non retenus dans l'enveloppe`],removed:selected.filter(v=>v.score>=80).slice(0,5).map(v=>`${v.immat} · ${v.agence} · score ${v.score}`),deferred:excluded.slice(0,8).map(v=>`${v.immat} · ${v.excludeReason||'report'}`)};},
  justifyVehicle(v,strategyId){const parts=[]; if(v.score>=80)parts.push(`criticité élevée (${v.score}/100)`); if((v.age||0)>9)parts.push(`âge ${v.age.toFixed(1)} ans`); if(v.ctDays!=null&&v.ctDays<0)parts.push('CT dépassé'); else if(v.ctDays!=null&&v.ctDays<=60)parts.push(`CT dans ${v.ctDays} jours`); if(v.typeNorm==='Ambulance')parts.push('ambulance stratégique'); if(strategyId==='financier')parts.push('ratio économies/CAPEX favorable'); if(strategyId==='equilibre')parts.push('agence prioritaire pour l’équilibre territorial'); return 'Remplacement recommandé : '+(parts.join(' · ')||'priorité multicritère')+'.';},
  fiveYearPlan(vehicles,best,constraints){const params=SomaSimulator.readParams?SomaSimulator.readParams():SomaSimulator.defaults; const already=new Set((best?.vehiculesRetenus||[]).map(v=>v.id)); let pool=vehicles.filter(v=>!already.has(v.id)).map(v=>this.decorate(v,params,this.agencyRisk(vehicles),this.strategies.patrimoine)).sort((a,b)=>(b.score-a.score)||(b.age-a.age)); const plan=[]; let previous=vehicles; for(let year=2027;year<=2031;year++){let rows=year===2027?(best?.vehiculesRetenus||[]):[]; if(year>2027){let budget=Math.max(350000,Math.round((constraints.budgetMax||2000000)*0.45)); while(pool.length&&budget>=pool[0].net){const v=pool.shift(); rows.push(v); budget-=v.net; if(rows.length>Math.ceil(vehicles.length/10))break;}} const after=this.afterVehicles(previous,rows); const stats=SomaDashboard.stats(after); const health=SomaExecutive.healthIndex(after,stats,SomaExecutive.agencyScores(after)); const capex=rows.reduce((s,v)=>s+v.net,0); const savings=rows.reduce((s,v)=>s+(v.score>=80?1500:v.score>=60?800:350),0); plan.push({year,count:rows.length,capex,ageAvg:stats.ageAvg,health:health.score,critical:stats.critical,amort:capex/(constraints.amortYears||5),savings,remaining:pool.length}); previous=after;} return plan;},
  patrimony(vehicles,strategies,plan,constraints){const avgNet=Object.values(SomaSimulator.defaults.types).reduce((s,t)=>s+(t.cost-t.resale),0)/Object.keys(SomaSimulator.defaults.types).length; const estimated=vehicles.length*avgNet; const replaced=(strategies[0]?.vehiculesRetenus||[]).reduce((s,v)=>s+v.net,0); return {estimatedValue:estimated,replacedValue:replaced,remainingValue:Math.max(0,estimated-replaced),cumulatedInvest:plan.reduce((s,p)=>s+p.capex,0),renewalRate:vehicles.length?Math.round((plan.reduce((s,p)=>s+p.count,0)/vehicles.length)*1000)/10:0,agingIndex:Math.round(SomaUtils.avg(vehicles.map(v=>v.age||0))*10)/10,renewalIndex:Math.round((plan[0]?.health||0)*10)/10};},
  explanations(rows,best,plan,patrimony){const byAudience={dg:'',df:'',dr:'',parc:''}; if(!best){Object.keys(byAudience).forEach(k=>byAudience[k]='Importer les données du parc pour produire l’analyse.'); return byAudience;} const topAg=Object.entries(best.repartitionParAgence).sort((a,b)=>b[1]-a[1]).slice(0,3).map(x=>x[0]).join(', ')||'aucune agence dominante'; byAudience.dg=`La stratégie ${best.strategyName} offre le meilleur compromis global : ${best.vehiculesRetenus.length} véhicules renouvelés, Health Index ${best.statsAvant.health}/100 → ${best.statsApres.health}/100, CAPEX net ${SomaUtils.money(best.investissementNet)}. Elle concentre l’effort sur ${topAg}.`;
    byAudience.df=`L’arbitrage représente ${SomaUtils.money(best.investissementNet)} de CAPEX net, soit ${SomaUtils.money(best.impact.amortAnnual)} d’amortissement annuel estimé. Les économies d’entretien sont estimées à ${SomaUtils.money(best.impact.economies)} par an.`;
    byAudience.dr=`Les agences les plus concernées sont ${topAg}. Les véhicules exclus le sont principalement pour plafond budgétaire ou lissage pluriannuel, afin de réduire les pics d’investissement.`;
    byAudience.parc=`La priorité opérationnelle porte sur les véhicules critiques, les alertes réglementaires et les ambulances stratégiques. ${best.consequences.removed.length} risques majeurs sont supprimés dès 2027.`; return byAudience;},
  exportComex(){const a=this.compareStrategies(SomaApp.state.vehicles||[],this.readConstraints()); const data={module:'SOMA_PARC',version:'1.5',type:'COMEX_PREMIUM',decision:a.best,plan:a.plan,patrimony:a.patrimony,explanations:a.explanations}; SomaUtils.download('soma_parc_comex_v1_5.json',JSON.stringify(data,null,2),'application/json'); return data;},
  exportPowerPoint(){const a=this.compareStrategies(SomaApp.state.vehicles||[],this.readConstraints()); const slides=[{title:'Décision proposée',body:a.explanations.dg},{title:'Comparaison des stratégies',body:a.strategies.map(s=>`${s.strategyName}: ${SomaUtils.money(s.investissementNet)}, HI ${s.statsApres.health}/100`)},{title:'Plan 5 ans',body:a.plan},{title:'Impacts financiers',body:a.explanations.df}]; SomaUtils.download('soma_parc_powerpoint_v1_5.json',JSON.stringify({module:'SOMA_PARC',version:'1.5',slides},null,2),'application/json');},
  loadConfig(){try{return JSON.parse(localStorage.getItem('soma_parc_score_admin')||'null')||SomaScore.cfg;}catch(e){return SomaScore.cfg;}},
  saveConfig(cfg){localStorage.setItem('soma_parc_score_admin',JSON.stringify(cfg)); SomaScore.cfg=cfg; SomaScore.cacheKey=null; if(window.SomaApp){SomaApp.state.vehicles.forEach(v=>SomaParser.enrich(v,SomaApp.settings)); SomaApp.render();}}
};

window.SomaOptimizerUI={
  init(){this.bind(); this.patchApp(); this.render();},
  bind(){document.getElementById('btnGoOptimizer')?.addEventListener('click',()=>document.getElementById('optimizer')?.scrollIntoView({behavior:'smooth'})); document.getElementById('btnRunOptimizer')?.addEventListener('click',()=>this.render(true)); document.getElementById('btnExportComexV15')?.addEventListener('click',()=>SomaOptimizer.exportComex()); document.getElementById('btnExportPptV15')?.addEventListener('click',()=>SomaOptimizer.exportPowerPoint()); document.getElementById('btnSaveScoreAdmin')?.addEventListener('click',()=>this.saveScoreAdmin()); document.getElementById('btnResetScoreAdmin')?.addEventListener('click',()=>this.renderScoreAdmin(true)); ['optBudget','optMaxVehicles','optAgencyCap','optRegionCap','optTypeCap','optMinAmb','optMinVsl','optAgeTarget','optHealthTarget'].forEach(id=>document.getElementById(id)?.addEventListener('change',()=>this.render(true)));},
  patchApp(){const wait=()=>{if(!window.SomaApp||SomaApp.__optimizerPatched)return; const old=SomaApp.render.bind(SomaApp); SomaApp.render=function(){old(); setTimeout(()=>SomaOptimizerUI.render(),0);}; const oldExpose=SomaApp.exposeApi.bind(SomaApp); SomaApp.exposeApi=function(){oldExpose(); Object.assign(window.SomaParc,{optimize:(c)=>SomaOptimizer.compareStrategies(SomaApp.state.vehicles,c||SomaOptimizer.readConstraints()).best,compareStrategies:(c)=>SomaOptimizer.compareStrategies(SomaApp.state.vehicles,c||SomaOptimizer.readConstraints()),getExecutiveDecision:()=>SomaOptimizer.compareStrategies(SomaApp.state.vehicles,SomaOptimizer.readConstraints()).explanations.dg,getInvestmentPlan:()=>SomaOptimizer.compareStrategies(SomaApp.state.vehicles,SomaOptimizer.readConstraints()).plan,getConstraints:()=>SomaOptimizer.readConstraints(),getOptimizer:()=>SomaOptimizer,exportComex:()=>SomaOptimizer.exportComex()});}; SomaApp.exposeApi(); SomaApp.__optimizerPatched=true;}; setTimeout(wait,0);},
  analysis(){const vehicles=window.SomaApp?.state?.vehicles||[]; return SomaOptimizer.compareStrategies(vehicles,SomaOptimizer.readConstraints());},
  render(force=false){const root=document.getElementById('optimizer'); if(!root)return; const vehicles=window.SomaApp?.state?.vehicles||[]; if(!vehicles.length){['strategyCompareV15','strategyConseqV15','fiveYearPlanV15','patrimonialKpis','audienceSummaries','comexPremiumV15'].forEach(id=>{const el=document.getElementById(id); if(el)el.innerHTML='<div class="emptyState">Importe un fichier ou charge la démo pour activer le copilote stratégique.</div>';}); this.renderScoreAdmin(); return;} const a=this.analysis(); this.renderStrategies(a); this.renderConsequences(a.best); this.renderPlan(a); this.renderPatrimony(a); this.renderSummaries(a); this.renderComex(a); this.renderScoreAdmin();},
  renderStrategies(a){const box=document.getElementById('strategyCompareV15'); if(!box)return; box.innerHTML=a.strategies.map(s=>`<article class="strategyCard ${a.best?.id===s.id?'best':''}"><div class="strategyHead"><b>${SomaUtils.escape(s.strategyName)}</b><span>${a.best?.id===s.id?'Meilleur compromis':'Alternative'}</span></div><p>${SomaUtils.escape(s.description)}</p><div class="strategyKpis"><span>${SomaUtils.money(s.investissementNet)}<small>CAPEX net</small></span><span>${s.vehiculesRetenus.length}<small>véhicules</small></span><span>${s.statsApres.health}/100<small>Health</small></span><span>${s.impact.roi}%<small>ROI entretien</small></span></div><div class="budgetBar"><i style="width:${Math.min(100,SomaUtils.pct(s.investissementNet,Math.max(1,SomaOptimizer.readConstraints().budgetMax)))}%"></i></div></article>`).join(''); const t=document.getElementById('strategyTableV15'); if(t)t.innerHTML='<thead><tr>'+['Stratégie','CAPEX net','Remplacés','Âge','Health','Critiques restants','ROI','Score compromis'].map(h=>`<th>${h}</th>`).join('')+'</tr></thead><tbody>'+a.strategies.map(s=>`<tr class="${a.best?.id===s.id?'bestRow':''}"><td><b>${SomaUtils.escape(s.strategyName)}</b></td><td class="num">${SomaUtils.money(s.investissementNet)}</td><td class="num">${s.vehiculesRetenus.length}</td><td class="num">${s.statsAvant.ageAvg.toFixed(1)} → ${s.statsApres.ageAvg.toFixed(1)}</td><td class="num">${s.statsAvant.health} → ${s.statsApres.health}</td><td class="num">${s.statsApres.critical}</td><td class="num">${s.impact.roi}%</td><td class="num">${s.compromiseScore}</td></tr>`).join('')+'</tbody>';},
  renderConsequences(best){const el=document.getElementById('strategyConseqV15'); if(!el||!best)return; const block=(title,arr,cls)=>`<article class="consequence ${cls}"><h3>${title}</h3>${(arr||[]).map(x=>`<div>• ${SomaUtils.escape(String(x))}</div>`).join('')||'<div>—</div>'}</article>`; el.innerHTML=block('Ce qui est amélioré',best.consequences.improved,'good')+block('Ce qui est dégradé',best.consequences.degraded,'warn')+block('Risques acceptés',best.consequences.accepted,'blue')+block('Risques supprimés',best.consequences.removed,'good')+block('Investissements reportés',best.consequences.deferred,'warn');},
  renderPlan(a){const t=document.getElementById('fiveYearPlanV15'); if(!t)return; t.innerHTML='<thead><tr>'+['Année','CAPEX','Véhicules','Âge moyen','Health','Critiques','Amortissements','Économies','Reste'].map(h=>`<th>${h}</th>`).join('')+'</tr></thead><tbody>'+a.plan.map(p=>`<tr><td><b>${p.year}</b></td><td class="num">${SomaUtils.money(p.capex)}</td><td class="num">${p.count}</td><td class="num">${p.ageAvg.toFixed(1)}</td><td class="num">${p.health}/100</td><td class="num">${p.critical}</td><td class="num">${SomaUtils.money(p.amort)}</td><td class="num">${SomaUtils.money(p.savings)}</td><td class="num">${p.remaining}</td></tr>`).join('')+'</tbody>'; SomaCharts.bars('fiveYearCapexChartV15',a.plan.map(p=>({label:String(p.year),value:Math.round(p.capex/1000)})));},
  renderPatrimony(a){const p=a.patrimony; const el=document.getElementById('patrimonialKpis'); if(!el)return; el.innerHTML=[['Valeur estimée',SomaUtils.money(p.estimatedValue),'parc actuel'],['Valeur remplacée',SomaUtils.money(p.replacedValue),'stratégie 2027'],['Valeur restante',SomaUtils.money(p.remainingValue),'après arbitrage'],['Invest. cumulés 5 ans',SomaUtils.money(p.cumulatedInvest),'plan 2027-2031'],['Rythme renouvellement',p.renewalRate+' %','sur 5 ans'],['Indice vieillissement',p.agingIndex,'âge moyen'],['Indice renouvellement',p.renewalIndex+'/100','health projeté']].map(k=>`<div class="kpi"><div class="label">${k[0]}</div><div class="value">${k[1]}</div><div class="note">${k[2]}</div></div>`).join('');},
  renderSummaries(a){const e=a.explanations; const el=document.getElementById('audienceSummaries'); if(!el)return; el.innerHTML=[['Direction Générale',e.dg],['Directeur Financier',e.df],['Directeur Régional',e.dr],['Responsable Parc',e.parc]].map(x=>`<article class="summaryAudience"><h3>${x[0]}</h3><p>${SomaUtils.escape(x[1])}</p></article>`).join('');},
  renderComex(a){const el=document.getElementById('comexPremiumV15'); if(!el)return; el.innerHTML=`<div class="reportCover"><div>SOMA PARC V1.5</div><h2>Dossier COMEX Premium</h2><p>${SomaUtils.escape(a.explanations.dg)}</p></div>`+['Contexte','Diagnostic','Comparaison des stratégies','Recommandation finale','Plan d’investissement','Impacts financiers','Impacts opérationnels','Risques','Décisions proposées'].map(title=>`<section class="reportSection"><h3>${title}</h3><p>${SomaUtils.escape(this.reportText(title,a))}</p></section>`).join('');},
  reportText(title,a){const b=a.best; const m={Contexte:`Le parc analysé sert à préparer le budget de renouvellement 2027 et le plan 2027-2031.`,Diagnostic:`Health Index initial ${b?.statsAvant.health}/100, âge moyen ${b?.statsAvant.ageAvg.toFixed(1)} ans, ${b?.statsAvant.critical} véhicules critiques.`,['Comparaison des stratégies']:a.strategies.map(s=>`${s.strategyName}: ${SomaUtils.money(s.investissementNet)}, Health ${s.statsApres.health}/100`).join(' · '),['Recommandation finale']:`Retenir la stratégie ${b?.strategyName}, meilleur compromis selon les contraintes saisies.`,['Plan d’investissement']:`CAPEX cumulé 5 ans ${SomaUtils.money(a.plan.reduce((s,p)=>s+p.capex,0))}.`,['Impacts financiers']:a.explanations.df,['Impacts opérationnels']:a.explanations.parc,Risques:(b?.consequences.deferred||[]).slice(0,5).join(' · ')||'Risque résiduel maîtrisé.', ['Décisions proposées']:`Valider l’enveloppe ${SomaUtils.money(b?.investissementNet||0)}, arbitrer les reports et préparer l’intégration budgétaire SOMA.`}; return m[title]||'';},
  renderScoreAdmin(reset=false){const el=document.getElementById('scoreAdminV15'); if(!el)return; const cfg=reset?SomaScore.cfg:SomaOptimizer.loadConfig(); el.innerHTML=`<div class="grid c3 compactForm"><div><label>Âge > 9 ans</label><input id="admAgeGt9" type="number" value="${cfg.age?.gt9??30}"></div><div><label>CT dépassé</label><input id="admCtExpired" type="number" value="${cfg.ct?.expired??30}"></div><div><label>CT proche</label><input id="admCtSoon" type="number" value="${cfg.ct?.soon??15}"></div><div><label>Taximètre dépassé</label><input id="admTxExpired" type="number" value="${cfg.taximeter?.expired??15}"></div><div><label>Accident</label><input id="admAccident" type="number" value="${cfg.events?.accident??15}"></div><div><label>Dommage</label><input id="admDamage" type="number" value="${cfg.events?.damage??10}"></div></div><p class="hint">Ces paramètres sont stockés localement et préparent le futur écran d'administration SOMA.</p>`;},
  saveScoreAdmin(){const cfg=JSON.parse(JSON.stringify(SomaScore.cfg)); cfg.age.gt9=Number(document.getElementById('admAgeGt9').value)||cfg.age.gt9; cfg.ct.expired=Number(document.getElementById('admCtExpired').value)||cfg.ct.expired; cfg.ct.soon=Number(document.getElementById('admCtSoon').value)||cfg.ct.soon; cfg.taximeter.expired=Number(document.getElementById('admTxExpired').value)||cfg.taximeter.expired; cfg.events.accident=Number(document.getElementById('admAccident').value)||cfg.events.accident; cfg.events.damage=Number(document.getElementById('admDamage').value)||cfg.events.damage; SomaOptimizer.saveConfig(cfg);}
};

document.addEventListener('DOMContentLoaded',()=>SomaOptimizerUI.init());
