window.SomaSimulator={
  defaults:{
    types:{
      'Ambulance':{cost:95000,resale:9000,priority:5},
      'VSL':{cost:45000,resale:4500,priority:3},
      'Taxi':{cost:45000,resale:4500,priority:3},
      'TPMR':{cost:65000,resale:6500,priority:2},
      'Funéraire':{cost:70000,resale:7000,priority:1},
      'Autre':{cost:50000,resale:5000,priority:1}
    },
    amortYears:5,
    agencyCap:0,
    savingsCritical:1500,
    savingsRisk:800
  },
  cache:new Map(),
  normalizeType(type){const n=SomaUtils.norm(type||''); if(n.includes('ambu')||n.includes('assu'))return 'Ambulance'; if(n.includes('vsl'))return 'VSL'; if(n.includes('taxi'))return 'Taxi'; if(n.includes('tpmr'))return 'TPMR'; if(n.includes('fun'))return 'Funéraire'; return 'Autre';},
  readParams(){const types={}; Object.keys(this.defaults.types).forEach(t=>{types[t]={cost:Number(document.getElementById('simCost_'+this.key(t))?.value)||this.defaults.types[t].cost,resale:Number(document.getElementById('simResale_'+this.key(t))?.value)||this.defaults.types[t].resale,priority:Number(document.getElementById('simPriority_'+this.key(t))?.value)||this.defaults.types[t].priority};}); return {budgetLibre:Number(document.getElementById('budgetRange')?.value)||0,agencyCap:Number(document.getElementById('agencyCap')?.value)||0,amortYears:Number(document.getElementById('amortYears')?.value)||5,types};},
  key(s){return SomaUtils.norm(s).replace(/[^a-z0-9]/g,'');},
  initInputs(){const box=document.getElementById('typeBudgetInputs'); if(!box)return; box.innerHTML='<h3>Coûts moyens par type</h3>'+Object.entries(this.defaults.types).map(([t,c])=>`<div class="typeBudgetRow"><b>${t}</b><label>Coût</label><input id="simCost_${this.key(t)}" type="number" value="${c.cost}"><label>Reprise</label><input id="simResale_${this.key(t)}" type="number" value="${c.resale}"><label>Priorité</label><input id="simPriority_${this.key(t)}" type="number" min="0" max="5" value="${c.priority}"></div>`).join('');},
  makeScenarios(vehicles,params){if(!vehicles.length)return []; const criticalBudget=this.estimateBudget(vehicles.filter(v=>v.score>=80),params); const riskBudget=this.estimateBudget(vehicles.filter(v=>v.score>=60),params); const avgType=this.avgCost(params); const defs=[{id:'minimal',name:'Minimal',budget:Math.min(criticalBudget,Math.max(criticalBudget,avgType*1)),mode:'critical',limitScore:80},{id:'recommande',name:'Recommandé',budget:Math.max(riskBudget*.65,criticalBudget),mode:'recommended',limitScore:60},{id:'ambitieux',name:'Ambitieux',budget:Math.max(riskBudget,criticalBudget*1.5),mode:'ambitious',limitScore:45},{id:'libre',name:'Budget libre',budget:params.budgetLibre,mode:'free',limitScore:40}]; return defs.map(d=>this.runScenario(vehicles,d,params));},
  avgCost(params){const vals=Object.values(params.types).map(t=>Math.max(0,t.cost-t.resale)); return vals.reduce((a,b)=>a+b,0)/(vals.length||1);},
  estimateBudget(vehicles,params){return vehicles.reduce((s,v)=>{const t=params.types[this.normalizeType(v.type)]||params.types.Autre; return s+Math.max(0,t.cost-t.resale);},0);},
  cacheKey(vehicles,def,params){return [vehicles.length,vehicles.map(v=>`${v.id}:${v.score}:${v.age}:${v.ctDays}:${v.taxiDays}`).join('|'),JSON.stringify(def),JSON.stringify(params)].join('§');},
  runScenario(vehicles,def,params){const key=this.cacheKey(vehicles,def,params); if(this.cache.has(key))return this.cache.get(key); const statsAvant=this.stats(vehicles); const agencySelected={}; let budgetLeft=def.budget; const candidates=vehicles.filter(v=>v.score>=def.limitScore&&v.decision!=='Conserver').map(v=>this.decorate(v,params)); candidates.sort((a,b)=>this.priorityScore(b,params)-this.priorityScore(a,params)); const retenus=[]; const reportes=[]; for(const item of candidates){const cap=params.agencyCap||0; if(cap&&((agencySelected[item.agence]||0)+item.net>cap)){reportes.push({...item,reportReason:'Plafond agence atteint'}); continue;} if(item.net<=budgetLeft){retenus.push(item); budgetLeft-=item.net; agencySelected[item.agence]=(agencySelected[item.agence]||0)+item.net;}else reportes.push({...item,reportReason:'Budget insuffisant'});}
    const retainedIds=new Set(retenus.map(v=>v.id)); const afterVehicles=vehicles.map(v=>retainedIds.has(v.id)?{...v,age:0,score:0,decision:'Remplacé'}:v); const statsApres=this.stats(afterVehicles); const budgetBrut=retenus.reduce((s,v)=>s+v.replaceCost,0); const repriseEstimee=retenus.reduce((s,v)=>s+v.resale,0); const investissementNet=budgetBrut-repriseEstimee; const repartitionParAgence=SomaUtils.countBy(retenus,'agence'); const repartitionParType=SomaUtils.countBy(retenus,'typeNorm'); const scenario={id:def.id,scenarioName:def.name,budgetDisponible:def.budget,budgetBrut,repriseEstimee,investissementNet,vehiculesRetenus:retenus,vehiculesReportes:reportes,statsAvant,statsApres,repartitionParAgence,repartitionParType,budgetRestant:budgetLeft,impact:this.impact(retenus,investissementNet,params)}; this.cache.set(key,scenario); return scenario;},
  decorate(v,params){const typeNorm=this.normalizeType(v.type); const p=params.types[typeNorm]||params.types.Autre; return {...v,typeNorm,replaceCost:p.cost,resale:p.resale,net:Math.max(0,p.cost-p.resale),selectionReason:this.reason(v,typeNorm)};},
  priorityScore(v,params){const t=params.types[this.normalizeType(v.type)]||params.types.Autre; const reg=(v.ctDays!=null&&v.ctDays<0?30:0)+(v.ctDays!=null&&v.ctDays<=60&&v.ctDays>=0?15:0)+(v.taxiDays!=null&&v.taxiDays<0?15:0); return (v.score||0)*100+(v.age||0)*8+reg*3+(t.priority||0)*25;},
  reason(v,typeNorm){const r=[]; if(v.score>=80)r.push('Score critique supérieur à 80'); else if(v.score>=60)r.push('Score à risque supérieur à 60'); if(v.ctDays!=null&&v.ctDays<0)r.push('CT dépassé'); else if(v.ctDays!=null&&v.ctDays<=60&&v.ctDays>=0)r.push('CT proche'); if(v.taxiDays!=null&&v.taxiDays<0)r.push('Taximètre dépassé'); if((v.age||0)>9)r.push('Véhicule âgé de plus de 9 ans'); if(typeNorm==='Ambulance')r.push('Ambulance prioritaire'); return r.join(' · ')||'Priorité multicritère';},
  stats(vehicles){const ages=vehicles.map(v=>v.age).filter(Number.isFinite); return {count:vehicles.length,ageAvg:SomaUtils.avg(ages),critical:vehicles.filter(v=>v.score>=70||v.decision==='Remplacer').length};},
  impact(retenus,net,params){const amortYears=params.amortYears||5; const saving=retenus.reduce((s,v)=>s+(v.score>=80?this.defaults.savingsCritical:this.defaults.savingsRisk),0); const amortAnnual=net/amortYears; return {capexBrut:retenus.reduce((s,v)=>s+v.replaceCost,0),reprises:retenus.reduce((s,v)=>s+v.resale,0),capexNet:net,amortAnnual,amortMonthly:amortAnnual/12,savingsMaintenance:saving,netImpactYear:amortAnnual-saving};},
  summary(s){if(!s)return 'Aucun scénario disponible.'; const topAg=Object.entries(s.repartitionParAgence).sort((a,b)=>b[1]-a[1]).slice(0,3).map(x=>x[0]).join(', ')||'aucune agence dominante'; return `Le scénario ${s.scenarioName.toLowerCase()} prévoit le remplacement de ${s.vehiculesRetenus.length} véhicules pour un investissement net estimé à ${SomaUtils.money(s.investissementNet)}. Il permettrait de réduire le nombre de véhicules critiques de ${s.statsAvant.critical} à ${s.statsApres.critical} et d’abaisser l’âge moyen du parc de ${s.statsAvant.ageAvg.toFixed(1)} à ${s.statsApres.ageAvg.toFixed(1)} ans. Les agences les plus concernées sont ${topAg}.`;},
  exportJson(s){return {module:'SOMA_PARC',version:'1.4',anneeBudgetaire:2027,scenario:{nom:s.scenarioName,budgetBrut:s.budgetBrut,repriseEstimee:s.repriseEstimee,investissementNet:s.investissementNet,vehicules:s.vehiculesRetenus.map(v=>({immat:v.immat,agence:v.agence,type:v.type,score:v.score,age:v.age,coutRemplacement:v.replaceCost,repriseEstimee:v.resale,investissementNet:v.net,raison:v.selectionReason}))}};}
};
